import { artlyDemoVideo } from "@/lib/hero"
import { orchiaShowcase } from "@/lib/orchia"
import { legacyProjectIndex, appendedProjectSlugs } from "@/lib/legacy-project-index"

export type Project = {
  id: number
  title: string
  subtitle: string
  tag?: string
  year?: number
  discipline: string
  slug: string
  flag?: string
  /** Optional cursor preview for projects without a detail-panel image. */
  hoverImage?: string
  /** Intrinsic image dimensions reserve the panel's height before a lazy image loads. */
  imageSize?: [width: number, height: number]
  video?: string
  videoCaption?: string
  videoSize?: [width: number, height: number]
  demoUrl?: string
  body: string
  mount: string
  /** badge display name — the short form 05 prints in .bnm */
  short?: string
  /** badge descriptor line — 05's .bds */
  blurb?: string
  /** display-window rail: Format */
  kind?: string
  /** display-window rail: Stack */
  stack?: string
  /** display-window rail: Role */
  role?: string
  /** display-window rail: Proof — the row stays hidden when absent */
  proof?: string
}

export type Experience = {
  title: string
  org: string
  details: string[]
  label: string
  location: string
}

export type Capability = {
  group: string
  items: string
}

export type Meta = {
  name: string
  role: string
  positioning: string
  headline: string
  email: string
  github: string
  linkedin: string
  nyc: string
}

export const meta: Meta = {
  name: "Lingyi Zhou",
  role: "Robotics & Real-Time 3D Engineer",
  positioning: "I close the loop between perception and actuation — teleoperation, simulation, and real-time rendering for robots and spatial products.",
  headline: "Hardware → real-time graphics → shipped product, all three ends, closed by one person.",
  email: "zeroonelatte@gmail.com",
  github: "github.com/reatured",
  linkedin: "linkedin.com/in/lingyizhou",
  nyc: "New York, NY · open to remote",
}

const currentProjects: Project[] = [
  { id: 6,  title: "Orchia Studio", year: 2026, discipline: "agentic / product", slug: "orchia", flag: "flag-orchia", imageSize: [1600, 941],
    hoverImage: orchiaShowcase.workflowImage,
    subtitle: "Agentic workflows turn your story into social media videos.",
    body: "Orchia connects story planning, reference images, scene generation, and review in one video production workflow. Human feedback becomes the input for the next version, so a team can refine the story and its visual continuity across successive runs.",
    mount: "AI video platform", stack: "TypeScript · Next.js",
    role: "Founder at Orchia" },
  { id: 17, title: "Artly AI · Integrated Robotic Deployment System", year: 2026, discipline: "robotics / platform", slug: "artly-deployment", flag: "flag-artly", imageSize: [1600, 1377],
    video: artlyDemoVideo,
    videoCaption: "Demo video generated by Orchia Studio.",
    subtitle: "Author, validate, and deploy robot motion.",
    body: "An integrated robot deployment system combining 3D visualization, motion authoring, data validation, and debugging. Operators can prepare, validate, and deploy new robots, publish validated motion updates, and trace revisions to robot behaviors.",
    mount: "System showcase", stack: "React · Three.js / R3F · URDF · closed-chain IK · Keycloak",
    role: "Full Stack Software Engineer at Artly AI" },
  // Preserve the original demo URL; the browser demo and physical teleoperation are separate projects.
  { id: 1,  title: "RealHand · Robot Hand Web Demo", tag: "Flagship", year: 2025, discipline: "robotics / webgl", slug: "realhand-teleop", flag: "flag-realhand", imageSize: [1600, 900],
    demoUrl: "https://www.realhand.com/demo",
    subtitle: "Your camera brings a robot hand to life in the browser.",
    body: "An interactive robot hand demo on the RealHand website. Camera-based hand tracking lets visitors move a 3D hand model directly in the browser. MediaPipe detects 21 hand landmarks, with pose mapping and Three.js visualization across a registry of 31 URDF hand models.",
    mount: "interactive 3D demo",
    short: "RealHand", blurb: "Robot hand web demo · camera tracking",
    kind: "Interactive 3D demo", stack: "Three.js · MediaPipe · URDF hand models",
    role: "Browser demo development at RealHand" },
  { id: 18, title: "RealHand · Teleoperation", tag: "CES 2026", year: 2026, discipline: "robotics / xr", slug: "teleoperation",
    subtitle: "Two robot arms and hands, controlled through VR.",
    body: "A VR teleoperation system showcased live at CES 2026. Operators remotely control two robot arms and two dexterous hands through an integrated control surface, with input mapping, calibration, and live robot state visualization.",
    mount: "System showcase", stack: "Three.js · XR input · robot calibration",
    role: "Development, deployment, and live showcase at RealHand" },
  { id: 2,  title: "Snap AR Drawing Tool", tag: "In Snap docs", year: 2022, discipline: "spatial / cv", slug: "ar-drawing", flag: "flag-snap", imageSize: [1600, 900],
    subtitle: "Draw in the air with hand tracking on Spectacles.",
    body: "Hand tracking drives procedural mesh generation in real time on Spectacles. Solved texture stability across regenerated topology, then documented in Snap's Lens Studio 4.55.1 procedural-mesh developer documentation.",
    mount: "video",
    short: "Snap AR Drawing", blurb: "Procedural mesh from hand tracking",
    kind: "Video", stack: "Lens Studio · hand tracking · procedural mesh",
    role: "Built during Snap Inc. internship",
    proof: "Published in Snap developer docs · tested on Spectacles" },
  { id: 3,  title: "Marvel's Flerken AR Filter", tag: "Official", year: 2023, discipline: "spatial / campaign", slug: "flerken", flag: "flerken", imageSize: [1280, 2276],
    subtitle: "An official cat-detection effect for The Marvels.",
    body: "An official The Marvels campaign effect developed at Moviebill / Really AR, using cat detection and Flerken visual effects for TikTok and the Regal Cinema app.",
    mount: "video",
    short: "Marvel's Flerken", blurb: "Official The Marvels AR campaign",
    kind: "Video", stack: "Lens Studio · Effect House · object detection",
    role: "AR Developer at Moviebill / Really AR",
    proof: "Official The Marvels campaign · TikTok + Regal Cinema" },
  { id: 4,  title: "No Job Too Small", tag: "Top 1%", year: 2024, discipline: "graphics / unity", slug: "no-job-too-small", flag: "no-job-too-small", imageSize: [1280, 720],
    subtitle: "An oversized intern turns a tiny office into a physics playground.",
    body: "A collaborative LookAway Games entry for GMTK Game Jam 2024, ranked top 1% of 3,300+ entries. Lingyi served as Lead Coder for the gameplay, physics systems, and game architecture.",
    mount: "playable build",
    short: "No Job Too Small", blurb: "GMTK 2024 · Unity / HLSL toon pipeline",
    kind: "Playable build", stack: "Unity · C# · HLSL · Blender",
    role: "Lead Coder · LookAway Games",
    proof: "Top 1% of 3,300+ entries" },
  { id: 5,  title: "B612 Soccer", tag: "Top 2%", year: 2025, discipline: "graphics / physics", slug: "b612", flag: "b612-soccer", imageSize: [1280, 829],
    subtitle: "Soccer on a tiny planet, with custom spherical physics.",
    body: "Self-written spherical physics model driving a soccer game. Placed top 2% at GMTK 2025, the second consecutive year a 48-hour jam build outranked 98% of the field.",
    mount: "playable build" },
  { id: 7,  title: "Hardware Store Smart Search",        year: 2025, discipline: "product / full stack", slug: "hardware-store", flag: "hardware-store", imageSize: [1280, 720],
    subtitle: "A search and lead-generation tool for a hardware store.",
    body: "React and FastAPI lead-gen surface for a real hardware-store client. Delivered, live, in production.",
    mount: "live site" },
  { id: 8,  title: "Spaceman Rescue",                    year: 2025, discipline: "simulation / unity", slug: "spaceman", flag: "spaceman", imageSize: [1280, 660],
    subtitle: "A 3D space adventure with narrative puzzles.",
    body: "A Unity and Blender space adventure combining 3D modeling, narrative puzzles, and gameplay development.",
    mount: "video" },
  { id: 9,  title: "VR Experience on Quest",      year: 2024, discipline: "spatial / xr", slug: "vr-quest", flag: "vr-quest", imageSize: [1280, 720],
    subtitle: "Hands-on object interaction in six degrees of freedom.",
    body: "XR Interaction Toolkit on Oculus Quest. 6-DOF pick-and-place interaction demo.",
    mount: "video" },
  { id: 10, title: "VR Magic",         year: 2025, discipline: "graphics / vfx", slug: "vr-magic", flag: "vr-magic", imageSize: [1280, 720],
    subtitle: "Cast spells with hand gestures and real-time particles.",
    body: "Unity-based VR hand-tracking spellcasting with visual effects. A study in real-time particle systems and gesture recognition.",
    mount: "video" },
  { id: 11, title: "GoGreenNext Modular Map Tiles",     year: 2025, discipline: "graphics / blender", slug: "gogreennext", flag: "gogreennext", imageSize: [1280, 727],
    subtitle: "A modular landscape kit for an NYU game team.",
    body: "Blender environment kit for an NYU game team. Modular tile system with authored vegetation and terrain.",
    mount: "image set" },
  { id: 12, title: "3D City Poster Series",               year: 2024, discipline: "graphics / data", slug: "city-posters", flag: "poster-ny", imageSize: [1000, 1415],
    subtitle: "Real map data becomes large-format city portraits.",
    body: "Blender and Google Maps data rendered as A1 city posters. New York, San Francisco, Cologne, and Macau at their local time of day.",
    mount: "image set" },
  { id: 13, title: "No-Drill Curtain Hook",               year: 2024, discipline: "fabrication / cad", slug: "curtain-hook",
    hoverImage: "/previews/curtain-hook.jpeg",
    subtitle: "A renter-friendly curtain hook, from CAD to 3D print.",
    body: "Fusion 360 CAD to FDM print. A renter-friendly curtain hook tested on real hardware.",
    mount: "photo set" },
  { id: 14, title: "CuraLoop", year: 2025, discipline: "product / ai", slug: "curaloop",
    hoverImage: "/previews/curaloop.png",
    subtitle: "AI-assisted support for Alzheimer's caregivers.",
    body: "React Native, FastAPI, and Claude in a human-in-the-loop system for Alzheimer's caregivers. Built at a hackathon, with a live deploy.",
    mount: "live demo" },
  { id: 15, title: "Shader Archive — 11 GLSL Studies",    year: 2025, discipline: "graphics / glsl", slug: "shaders",
    hoverImage: "/previews/shaders.jpg",
    subtitle: "Eleven shader experiments in a custom WebGL2 renderer.",
    body: "Eleven self-hosted GLSL shaders behind a WebGL2 renderer written from scratch. ShaderToy-compatible uniforms, IntersectionObserver lazy start, DPR cap 2.",
    mount: "live shader" },
  { id: 16, title: "Drag Task In", year: 2025, discipline: "product / web", slug: "drag-task",
    hoverImage: "/previews/drag-task.png",
    subtitle: "A personal schedule, arranged by drag and drop.",
    body: "React, dnd-kit, FastAPI, and Supabase powering a drag-and-drop schedule assistant. Built to scratch a real personal-use itch.",
    mount: "live site" },
]

// The existing order stays intact; published January projects follow it.
// Keep current slugs for incoming links and current flagship title corrections.
export const projects: Project[] = [
  ...currentProjects.map(project => {
    const source = legacyProjectIndex[project.slug]
    if (!source) return project
    const stack = source.stack
    return {
      ...project,
      body: source.overview,
      role: source.role,
      stack: stack || project.stack,
      ...(project.slug === "flerken" || project.slug === "no-job-too-small" || project.slug === "hardware-store"
        ? { subtitle: source.subtitle } : {}),
    }
  }),
  ...appendedProjectSlugs.map((slug, index): Project => {
    const source = legacyProjectIndex[slug]!
    return {
      id: 19 + index,
      slug,
      title: source.title,
      subtitle: source.subtitle,
      year: source.year ?? undefined,
      discipline: source.discipline,
      body: source.overview,
      role: source.role,
      stack: source.stack,
      hoverImage: source.hoverImage ?? undefined,
      mount: "Project gallery",
    }
  }),
]

// Professional Experience from the user-supplied Lingyi-Zhou-Resume-20260919-01 (reference/Lingyi-Zhou-Resume-20260919-01.html).
export const experiences: Experience[] = [
  {
    title: "Founder & Software Engineer", org: "Orchia", label: "Jul 2026 — Present", location: "Seattle, WA",
    details: [
      "Engineered and launched a TypeScript and Next.js video production application that lets studio partners configure agent workflows to turn an initial story into a finished video, reducing manual production effort.",
      "Designed responsive React workflow editors with editable nodes, connections, and live execution status, helping users configure and monitor video generation on desktop and mobile.",
      "Connected the editor to persistent workflow state, letting users inspect execution, revise selected stages, and resume generation without restarting completed work.",
      "Worked with studio partners to prototype interfaces in Figma and prioritize iterative product releases from feedback and generation data, delivering updates through CI/CD.",
    ],
  },
  {
    title: "Full Stack Software Engineer", org: "Artly AI", label: "Nov 2025 — Present", location: "Seattle, WA",
    details: [
      "Designed and deployed a React and Three.js robot motion authoring and validation application that let non-engineering operators create, inspect, validate, and deploy motion updates without routine engineering handoffs.",
      "Observed and trained operators to identify friction in motion authoring and deployment, then used their feedback and Figma prototypes to ship successive improvements to responsive interfaces for desktop, phone, and iPad.",
      "Improved web 3D loading and interaction responsiveness in the motion editor so operators could inspect and revise robot behaviors smoothly.",
      "Integrated the TypeScript 3D editor with existing Python services and databases, adding revision tracking for motion updates while maintaining AWS CI/CD and production monitoring.",
      "Shipped AI assisted authoring that generated robot behavior trees from existing templates and motion data, reducing manual setup while preserving operator review and validation before deployment.",
      "Delivered a 24/7 feedback ingestion and triage pipeline over a Discord corpus of 220K+ messages and 36K+ media assets using RAG and vector search to group and route user reported issues, reducing reliance on direct engineer support.",
    ],
  },
  {
    title: "Software Engineer", org: "RealHand Inc.", label: "Jun 2025 — Jan 2026", location: "Seattle, WA",
    details: [
      "Led development and deployment of a VR teleoperation system controlling two robot arms and two dexterous hands, taking it from an integrated prototype to a live CES 2026 demonstration on physical hardware.",
      "Shipped a Three.js robot hand demo on the company website that let visitors control a 3D model through camera based hand tracking.",
      "Developed a Python integration system for headset startup, robot calibration, and live status, passing XR state into the existing control stack over ZeroMQ/TCP so operators could prepare and troubleshoot the CES demonstration.",
      "Normalized camera and glove hand poses into a shared joint representation for 3D hand models and physical robot hands.",
    ],
  },
  {
    title: "Game Engine Engineer", org: "Moviebill", label: "Aug 2023 — Aug 2024", location: "Los Angeles, CA",
    details: [
      "Implemented Unity Editor tools with drag and drop workflows and difficulty controls so designers could create and configure levels themselves, reducing their dependence on engineers for monthly content releases.",
      "Maintained an AR game distribution app that let players access and launch published experiences on iOS, Apple Vision Pro, and Quest 3.",
      "Developed reusable mobile AR physics and interaction components, including rope simulation and object manipulation, reducing repeated implementation across new experiences.",
    ],
  },
  {
    title: "AR Engine Engineer Intern", org: "Snap Inc.", label: "May 2022 — Aug 2022", location: "Mountain View, CA",
    details: [
      "Designed and shipped an official Lens Studio plugin that exposed real time procedural mesh generation and hand interaction through a configurable JavaScript API for external creators.",
      "Created the official developer guide, samples, and tutorials to help external creators adopt the API in interactive experiences.",
      "Launched an AR drawing Lens with procedural geometry, hand tracking, and gesture detection that reached 200K plays and views in its first month.",
    ],
  },
]

export const capabilities: Capability[] = [
  { group: "Robotics", items: "Teleoperation · URDF · MediaPipe · physics simulation · CAD / FDM" },
  { group: "Graphics", items: "Three.js / R3F · WebGL2 · GLSL · HLSL · Unity · Blender · Geometry Nodes" },
  { group: "Spatial", items: "AR / VR · hand tracking · Lens Studio · Effect House · XR Interaction Toolkit" },
  { group: "Platform", items: "React · TypeScript · FastAPI · Postgres / Supabase · Vercel · GitHub Actions" },
]
